using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using SCS.Core;

internal static class V2Cases
{
    private static void Check(bool value, string message = "Assertion failed") { if (!value) throw new Exception(message); }
    public static void Run(Action<string, Action> test, string root)
    {
        var cat = SupportedCatalog.Create(); var compile = new ProfileCompiler(cat);
        var profile = ProfileRecord.CreateDefault(ProfileId.Profile1, cat);
        CompileResult With(string id, SettingValue value) => compile.Compile(profile.WithValues(profile.Values.SetItem(id, value)));
        var baseline = compile.Compile(profile);
        test("corrected catalogue owns exactly 154 targets and 20 settings", () => { Check(cat.Supported.Length == 20); Check(baseline.Success && baseline.Outputs.Length == 154); Check(baseline.Outputs.Select(o => o.Target.Identity).Distinct().Count() == 154); });
        test("Vanilla output exactly reproduces all documented baseline lines in order", () =>
        {
            var assembly=typeof(SupportedCatalog).Assembly;using var stream=assembly.GetManifestResourceStream(assembly.GetManifestResourceNames().Single(n=>n.EndsWith("catalog-baselines.json")))!;
            var rows=JsonSerializer.Deserialize<SupportedCatalog.BaselineRow[]>(stream)!;
            var text=string.Join("\r\n",rows.OrderBy(r=>r.Paragraph).Select(r=>$"set {r.Class} {r.Property} {r.Original}"))+"\r\n";
            Check(baseline.Text==text,"Vanilla differs from supplied document");
            File.WriteAllBytes(Path.Combine(root,"SCS_Vanilla.txt"),Encoding.ASCII.GetBytes(text));
        });
        test("crafting restores base before buildables and exceptions; 58 commands",()=>{var o=baseline.Outputs.Where(o=>o.SettingId=="CraftSpeed").ToArray();Check(o.Length==58);Check(o[0].Target.ClassName=="ColdInventoryItem"&&o[1].Target.ClassName=="ColdInventoryItem_Buildable");Check(o.Single(t=>t.Target.ClassName=="ColdInventoryItem_Buildable_GarageDoor").Value.Number==60);});
        test("crafting x100 uses integer seconds and signals saturation",()=>{var o=With("CraftSpeed",SettingValue.Numeric(100)).Outputs.Where(o=>o.SettingId=="CraftSpeed").ToArray();Check(o.All(o=>o.Value.Number>=1&&o.Value.Number==decimal.Truncate(o.Value.Number!.Value)));Check(o.Any(o=>o.Saturated));});
        test("loot keeps entry duplicates classes and chances",()=>{var result=With("CrateYield",SettingValue.Numeric(5));Check(result.Success);foreach(var o in result.Outputs.Where(o=>o.SettingId=="CrateYield")){var count=o.FormattedValue.Split("ItemClass=").Length-1;Check(count==o.Target.LootItems.Length);Check(!o.FormattedValue.Contains('\n'));}Check(!With("CrateYield",SettingValue.Numeric(100)).Success);});
        test("boar restores PorkChops and Fat 3-4; moose Tier6 is included",()=>{Check(baseline.Text.Contains("set ColdBoarPawn LootItemsTier1 ((ItemClass=Class'ColdGame.ColdInventoryItem_PorkChops',Chance=100,countMin=1,countMax=1))"));Check(baseline.Text.Contains("set ColdBoarPawn LootItemsTier2 ((ItemClass=Class'ColdGame.ColdInventoryItem_Fat',Chance=100,countMin=3,countMax=4))"));Check(baseline.Text.Contains("set ColdMoosePawn LootItemsTier6"));Check(!With("ButcherYield",SettingValue.Numeric(100)).Success);});
        test("passive toggle ON and OFF restore all perception exceptions",()=>{var on=With("PassiveWildlife",SettingValue.Logical(true));Check(on.Success&&on.Outputs.Where(o=>o.SettingId=="PassiveWildlife").All(o=>o.Value.Number==1));var off=baseline.Outputs.Where(o=>o.SettingId=="PassiveWildlife").ToArray();Check(off.Length==11&&off[0].Target.ClassName=="ColdAnimalPawn");Check(off.Single(o=>o.Target.ClassName=="ColdEaglePawn").Value.Number==13000);});
        test("wood and crop x100 compile; excluded systems have no controls",()=>{Check(With("WoodYield",SettingValue.Numeric(100)).Success);Check(With("CropHarvestYield",SettingValue.Numeric(100)).Success);Check(!cat.Definitions.Any(d=>d.Id.Contains("Mining")||d.Id.Contains("Bee")||d.Id=="FishingYield"||d.Id=="RefineryLasers"));});
        test("trap and refinery safety limits are enforced",()=>{Check(!With("TrapAttractionRadius",SettingValue.Numeric(600000)).Success);Check(!With("RefiningSpeed",SettingValue.Numeric(100)).Success);Check(With("RefiningSpeed",SettingValue.Numeric(50)).Outputs.Single(o=>o.SettingId=="RefiningSpeed").Value.Number==1);Check(With("TrapAttemptSpeed",SettingValue.Numeric(100)).Outputs.Where(o=>o.SettingId=="TrapAttemptSpeed").Select(o=>o.Value.Number).Order().SequenceEqual(new decimal?[]{4,4,7,7}));});
        test("negative energy signs and Overdrive ratios survive",()=>{var o=With("MassPowerConsumption",SettingValue.Numeric(.1m)).Outputs.Where(o=>o.SettingId=="MassPowerConsumption").ToArray();Check(o[0].Value.Number==-.25m&&o[1].Value.Number==-.75m);});
        test("old profiles migrate to corrected catalogue without losing user multipliers",()=>{var old=ProfileRecord.CreateDefault(ProfileId.Profile1,ReferenceCatalog.Create());old=old.WithValues(old.Values.SetItem(ReferenceCatalog.WeaponUpgradeSpeed,SettingValue.Numeric(4)));var result=ProfileMigrator.Migrate(old,cat);Check(result.Success&&result.Added.Length==18&&result.Profile!.Values[ReferenceCatalog.WeaponUpgradeSpeed].Number==4);});
        const string original="; keep comment\r\n[Engine.PlayerInput]\r\nBindings=(Name=\"F8\",Command=\"GBA_QuickSave\")\r\nBindings=(Name=\"F6\",Command=\"exec SCS_Test.txt\")\r\nBindings=(Name=\"F7\",Command=\"exec SCS_Profile1.txt | Jump\")\r\n[ColdGame.ColdPlayerInput]\r\nBindings=(Name=\"F9\",Command=\"GBA_QuickLoad\",Control=False,Shift=False,Alt=False,bIgnoreAlt=True)\r\n[Other]\r\nUnknown=value\r\n";
        GamePaths Fixture(string name, byte[]? bytes=null){var b=Path.Combine(root,name,"Binaries");Directory.CreateDirectory(Path.Combine(b,"Win64"));File.WriteAllBytes(Path.Combine(b,"Win64","Subsistence.exe"),[77,90]);var p=GamePaths.FromBinaries(b);Directory.CreateDirectory(Path.GetDirectoryName(p.InputIni)!);File.WriteAllBytes(p.InputIni,bytes??Encoding.UTF8.GetBytes(original));return p;}
        test("simple keys reject modifier combinations and block real actions",()=>{var doc=new InputIniDocument(Encoding.UTF8.GetBytes(original));Check(doc.Conflicts(new(ProfileId.Profile1,"F8")).Any(b=>b.FriendlyCommand=="Quick Save"));Check(doc.Conflicts(new(ProfileId.Profile1,"F6")).Length==1);Check(doc.Conflicts(new(ProfileId.Profile1,"F7")).Length==1);Check(!IniHotkeys.Validate(IniHotkeys.Defaults.SetItem(0,new(ProfileId.Profile1,"F10",true)),doc).IsEmpty);Check(IniHotkeys.BindingLine(IniHotkeys.Defaults[0]).EndsWith("bIgnoreCtrl=False,bIgnoreShift=False,bIgnoreAlt=False)"));});
        test("INI install/remove preserve unrelated bytes across encodings",()=>{foreach(var encoding in new Encoding[]{new UTF8Encoding(false),new UTF8Encoding(true),Encoding.Unicode,Encoding.BigEndianUnicode,Encoding.Latin1}){var bytes=encoding.GetPreamble().Concat(encoding.GetBytes(original.Replace("keep comment","keep café"))).ToArray();var doc=new InputIniDocument(bytes);var installed=new InputIniDocument(doc.Install(IniHotkeys.Defaults));Check(installed.RemoveScs().SequenceEqual(bytes),encoding.WebName);Check(installed.Bindings.Count(b=>b.IsScs)==10);}});
        test("EOF without newline and LF files roundtrip unchanged",()=>{foreach(var text in new[]{original.Replace("\r\n","\n"),"[Engine.PlayerInput]\r\n[ColdGame.ColdPlayerInput]\r\nUnknown=unchanged"}){var b=Encoding.UTF8.GetBytes(text);Check(new InputIniDocument(new InputIniDocument(b).Install(IniHotkeys.Defaults)).RemoveScs().SequenceEqual(b));}});
        test("conflicting modifiers and malformed foreign bindings are preserved and blocked",()=>{var bytes=Encoding.UTF8.GetBytes("[ColdGame.ColdPlayerInput]\nBindings=(Name=\"F10\",Command=\"foreign\",Control=True,bIgnoreCtrl=True)\nBindings=(Name=\"F11\",Command=\"foreign\")junk\n");var d=new InputIniDocument(bytes);Check(d.Conflicts(new(ProfileId.Profile1,"F10")).Length==1&&d.Conflicts(new(ProfileId.Profile1,"F11")).Length==1);Check(d.RemoveScs().SequenceEqual(bytes));});
        test("install idempotent; original backup and operation journals are retained",()=>{var p=Fixture("idempotent");var service=new IniHotkeyService(new Probe(false));Check(service.Install(p.InputIni,IniHotkeys.Defaults).Success);var first=File.ReadAllBytes(p.InputIni);var backup=Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini");Check(File.ReadAllBytes(backup).SequenceEqual(Encoding.UTF8.GetBytes(original)));Check(service.Install(p.InputIni,IniHotkeys.Defaults).Success&&File.ReadAllBytes(p.InputIni).SequenceEqual(first));var keys=IniHotkeys.Defaults.SetItem(0,new(ProfileId.Profile1,"Insert"));Check(service.Install(p.InputIni,keys).Success);Check(File.ReadAllBytes(backup).SequenceEqual(Encoding.UTF8.GetBytes(original)));Check(Directory.GetFiles(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-operation-*.json").Length==2);});
        test("remove preserves later edits and SCS_Test or mixed commands",()=>{var p=Fixture("remove");var svc=new IniHotkeyService(new Probe(false));Check(svc.Install(p.InputIni,IniHotkeys.Defaults).Success);File.AppendAllText(p.InputIni,"; added later\r\n");Check(svc.Remove(p.InputIni).Success);Check(File.ReadAllText(p.InputIni)==original+"; added later\r\n");Check(!svc.Remove(p.InputIni).Changed);});
        test("running game and unknown process state allow install update remove",()=>{var p=Fixture("running");var bytes=File.ReadAllBytes(p.InputIni);Check(new IniHotkeyService(new Probe(true)).Install(p.InputIni,IniHotkeys.Defaults).Success);Check(new IniHotkeyService(new UnknownProbe()).Install(p.InputIni,IniHotkeys.Defaults.SetItem(0,new(ProfileId.Profile1,"Insert"))).Success);Check(new IniHotkeyService(new Probe(true)).Remove(p.InputIni).Success);Check(File.ReadAllBytes(p.InputIni).SequenceEqual(bytes));});
        test("external INI edits before commit are not overwritten",()=>{var p=Fixture("external");Check(!new IniHotkeyService(beforeCommit:()=>File.AppendAllText(p.InputIni,"; external\r\n")).Install(p.InputIni,IniHotkeys.Defaults).Success);Check(File.ReadAllText(p.InputIni)==original+"; external\r\n");});
        test("failed commit keeps original INI and recoverable backup",()=>{var p=Fixture("failed");var svc=new IniHotkeyService(new Probe(false),new FailingCommitter());Check(!svc.Install(p.InputIni,IniHotkeys.Defaults).Success);Check(File.ReadAllText(p.InputIni)==original);Check(File.Exists(Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini")));});
        test("corrupted or unrelated backup blocks update",()=>{var p=Fixture("wrong-backup");File.WriteAllText(Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini"),"wrong");Check(!new IniHotkeyService(new Probe(false)).Install(p.InputIni,IniHotkeys.Defaults).Success);Check(File.ReadAllText(p.InputIni)==original);});
        test("installation validates the game executable and both coherent paths",()=>{var p=Fixture("paths");Check(GameInstallation.Verify(p.Binaries).Ready);File.Delete(Path.Combine(p.Binaries,"Win64","Subsistence.exe"));Check(!GameInstallation.Verify(p.Binaries).ProfilesReady);});
        test("combined installation preserves existing profiles and installs bindings",()=>{var p=Fixture("combined");File.WriteAllText(Path.Combine(p.Binaries,"SCS_Profile2.txt"),"existing external profile");var result=new ManagedProfiles().Install(cat,Enum.GetValues<ProfileId>().Select(id=>ProfileRecord.CreateDefault(id,cat)),p.Binaries,IniHotkeys.Defaults,new Probe(false));Check(result.Success,result.Message);Check(File.ReadAllText(Path.Combine(p.Binaries,"SCS_Profile2.txt"))=="existing external profile");Check(new InputIniDocument(File.ReadAllBytes(p.InputIni)).Bindings.Count(b=>b.IsScs)==10);});
        test("combined install rolls back only created unchanged profiles on INI backup failure",()=>{var p=Fixture("rollback");File.WriteAllText(Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini"),"unverified");File.WriteAllText(Path.Combine(p.Binaries,"SCS_Profile2.txt"),"keep");var result=new ManagedProfiles().Install(cat,Enum.GetValues<ProfileId>().Select(id=>ProfileRecord.CreateDefault(id,cat)),p.Binaries,IniHotkeys.Defaults,new Probe(false));Check(!result.Success);Check(!File.Exists(Path.Combine(p.Binaries,"SCS_Profile1.txt")));Check(File.ReadAllText(Path.Combine(p.Binaries,"SCS_Profile2.txt"))=="keep");});
        test("managed removal requires manifest and unchanged hash; backups retained",()=>{var p=Fixture("uninstall");var manager=new ManagedProfiles();Check(manager.Install(cat,Enum.GetValues<ProfileId>().Select(id=>ProfileRecord.CreateDefault(id,cat)),p.Binaries,IniHotkeys.Defaults,new Probe(false)).Success);Check(!manager.Remove(p.Binaries,["SCS_Profile1.txt"]).Success);Check(new IniHotkeyService(new Probe(false)).Remove(p.InputIni).Success);File.AppendAllText(Path.Combine(p.Binaries,"SCS_Profile2.txt"),"external");Check(!manager.Remove(p.Binaries,["SCS_Profile2.txt"]).Success);Check(!manager.Remove(p.Binaries,["SCS_Test.txt"]).Success);Check(manager.Remove(p.Binaries,["SCS_Profile1.txt"]).Success);Check(!File.Exists(Path.Combine(p.Binaries,"SCS_Profile1.txt")));Check(Directory.GetFiles(p.Binaries,"SCS_Profile1.txt.scs-removed-*.bak").Length==1);});
        test("unknown binding labels never expose commands",()=>{var d=new InputIniDocument(Encoding.UTF8.GetBytes(original));Check(d.Bindings.Single(b=>b.Name=="F6").FriendlyCommand=="existing game binding");Check(d.Bindings.Single(b=>b.Name=="F7").FriendlyCommand=="existing game binding");});
        test("Vanilla upgrade backs up old bytes and stamps catalogue without custom changes",()=>{var p=Fixture("vanilla-upgrade");var v=Path.Combine(p.Binaries,"SCS_Vanilla.txt");File.WriteAllText(v,"old vanilla");File.WriteAllText(Path.Combine(p.Binaries,"SCS_Profile1.txt"),"custom unchanged");VanillaMaintenance.Ensure(cat,p.Binaries);Check(VanillaMaintenance.Current(cat,p.Binaries));var backups=Directory.GetFiles(p.Binaries,"SCS_Vanilla.txt.scs-upgrade-*.bak");Check(backups.Length==1&&File.ReadAllText(backups[0])=="old vanilla");Check(File.ReadAllText(Path.Combine(p.Binaries,"SCS_Profile1.txt"))=="custom unchanged");Check(File.ReadAllText(Path.Combine(p.Binaries,"SCS_Vanilla.catalog.json")).Contains(cat.Version));VanillaMaintenance.Ensure(cat,p.Binaries);Check(Directory.GetFiles(p.Binaries,"*.bak").Length==1);});
        test("failed Vanilla replacement preserves old file and backup",()=>{var p=Fixture("vanilla-failure");var v=Path.Combine(p.Binaries,"SCS_Vanilla.txt");File.WriteAllText(v,"old");try{VanillaMaintenance.Ensure(cat,p.Binaries,new FailingCommitter());throw new Exception("Expected failure");}catch(IOException){}Check(File.ReadAllText(v)=="old");Check(Directory.GetFiles(p.Binaries,"*.bak").Length==1);Check(!File.Exists(Path.Combine(p.Binaries,"SCS_Vanilla.catalog.json")));});
        test("profile-only install leaves conflicting INI byte identical",()=>{var p=Fixture("profiles-only");var before=File.ReadAllBytes(p.InputIni);Check(new ManagedProfiles().InstallProfiles(cat,Enum.GetValues<ProfileId>().Select(id=>ProfileRecord.CreateDefault(id,cat)),p.Binaries).Success);Check(File.ReadAllBytes(p.InputIni).SequenceEqual(before));Check(ManagedProfiles.Names.All(n=>File.Exists(Path.Combine(p.Binaries,n))));});
        test("old saturated refinery profile migrates without changing effective interval",()=>{var old=ProfileRecord.CreateCustom(ProfileId.Profile1,"Old","2.0.0",cat.DefaultValues().SetItem("RefiningSpeed",SettingValue.Numeric(100)));var m=ProfileMigrator.Migrate(old,cat);Check(m.Success&&m.RequiresSave&&m.Profile!.Values["RefiningSpeed"].Number==50);Check(new ProfileCompiler(cat).Compile(m.Profile!).Outputs.Single(o=>o.SettingId=="RefiningSpeed").Value.Number==1);});
        test("wild gatherables and crop harvest have disjoint ownership; berries only crop",()=>{var wild=((ConsolePropertyBackend)cat.Definitions.Single(d=>d.Id=="VegetationYield").Backend).Targets;var crop=((ConsolePropertyBackend)cat.Definitions.Single(d=>d.Id=="CropHarvestYield").Backend).Targets;Check(!wild.Select(t=>(t.ClassName,t.PropertyName)).Intersect(crop.Select(t=>(t.ClassName,t.PropertyName))).Any());Check(crop.Any(t=>t.ClassName=="ColdLootVegetation_Berries")&&!wild.Any(t=>t.ClassName=="ColdLootVegetation_Berries"));});
        test("installed bindings become invalid when a foreign binding conflicts",()=>{var d=new InputIniDocument(Encoding.UTF8.GetBytes(original));var installed=new InputIniDocument(d.Install(IniHotkeys.Defaults));var session=IniHotkeyEditSession.Restore(IniHotkeys.Defaults,null);Check(session.Installed(installed));var changed=installed.Text.Replace("[Engine.PlayerInput]","[Engine.PlayerInput]\r\nBindings=(Name=\"F10\",Command=\"OtherAction\")");Check(!session.Installed(new InputIniDocument(Encoding.UTF8.GetBytes(changed))));});
        test("new hotkey sessions start unassigned and cannot install",()=>{var s=new IniHotkeyEditSession();Check(s.SavedAssignments.All(a=>a.KeyId=="")&&s.DraftAssignments.Length==5);Check(!IniHotkeys.Validate(s.DraftAssignments).IsEmpty);Check(IniHotkeys.Validate(s.DraftAssignments,allowUnassigned:true).IsEmpty);});
        test("legacy malformed duplicate and modifier assignments recover to editable slots",()=>{var s=IniHotkeyEditSession.Restore([new(ProfileId.Profile1,"F6"),new(ProfileId.Profile2,"F6"),new(ProfileId.Profile3,"BadKey"),new(ProfileId.Profile4,"F7",true)],null);Check(s.DraftAssignments.Length==5&&s.DraftAssignments.Count(a=>a.KeyId=="")==4);foreach(var a in IniHotkeys.Defaults)s.SetKey(a.ProfileId,a.KeyId);Check(IniHotkeys.Validate(s.DraftAssignments).IsEmpty);});
        test("clearing saved hotkeys releases all slots and survives restore",()=>{var s=IniHotkeyEditSession.Restore(IniHotkeys.Defaults,"old installation");s.ClearSavedAssignments();var restored=IniHotkeyEditSession.Restore(s.SavedAssignments,s.GeneratedBinariesPath);Check(restored.DraftAssignments.All(a=>a.KeyId=="")&&restored.GeneratedBinariesPath is null&&!restored.IsDirty);});
        test("occupied legacy assignment can be cleared and replaced without touching foreign bindings",()=>{var d=new InputIniDocument(Encoding.UTF8.GetBytes(original));var s=IniHotkeyEditSession.Restore(HotkeyCompiler.Defaults,null);Check(!IniHotkeys.Validate(s.DraftAssignments,d).IsEmpty);s.SetKey(ProfileId.Profile1,"");foreach(var a in IniHotkeys.Defaults)s.SetKey(a.ProfileId,a.KeyId);Check(IniHotkeys.Validate(s.DraftAssignments,d).IsEmpty);Check(new InputIniDocument(d.Install(s.DraftAssignments)).RemoveScs().SequenceEqual(d.OriginalBytes));});
        string LegacyText() => original.Replace("[ColdGame.ColdPlayerInput]", InputIniDocument.Begin+"\r\n"+string.Join("\r\n",IniHotkeys.Defaults.Select(IniHotkeys.BindingLine))+"\r\n"+InputIniDocument.End+"\r\n[ColdGame.ColdPlayerInput]");
        test("migration creates five matching pairs and preserves foreign bytes across encodings",()=>{foreach(var encoding in new Encoding[]{new UTF8Encoding(false),new UTF8Encoding(true),Encoding.Unicode,Encoding.BigEndianUnicode,Encoding.Latin1}){var bytes=encoding.GetPreamble().Concat(encoding.GetBytes(LegacyText())).ToArray();var p=Fixture("migration-"+encoding.WebName+encoding.GetPreamble().Length,bytes);var svc=new IniHotkeyService(new Probe(false));Check(!IniHotkeyEditSession.Restore(IniHotkeys.Defaults,null).Installed(new InputIniDocument(bytes)));var result=svc.MigrateLegacy(p.InputIni);Check(result.Success&&result.Changed,result.Message);var doc=new InputIniDocument(File.ReadAllBytes(p.InputIni));Check(doc.Bindings.Count(b=>b.IsScs)==10&&doc.HasCompleteLayout);Check(doc.RemoveScs().SequenceEqual(encoding.GetPreamble().Concat(encoding.GetBytes(original))));Check(File.ReadAllBytes(Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini")).SequenceEqual(bytes));Check(!svc.MigrateLegacy(p.InputIni).Changed);Check(!svc.Install(p.InputIni,IniHotkeys.Defaults).Changed);}});
        test("installation cleans duplicate SCS bindings from both sections without touching near matches",()=>{var text=LegacyText().Replace("[ColdGame.ColdPlayerInput]","[ColdGame.ColdPlayerInput]\r\n"+string.Join("\r\n",IniHotkeys.Defaults.Select(IniHotkeys.BindingLine)));var p=Fixture("migration-duplicate",Encoding.UTF8.GetBytes(text));Check(new IniHotkeyService(new Probe(false)).Install(p.InputIni,IniHotkeys.Defaults).Success);var doc=new InputIniDocument(File.ReadAllBytes(p.InputIni));Check(doc.Bindings.Count(b=>b.IsScs)==10);Check(doc.RemoveScs().SequenceEqual(Encoding.UTF8.GetBytes(original)));});
        test("migration refuses conflict and incomplete legacy assignments without removing anything",()=>{foreach(var text in new[]{LegacyText().Replace("Name=\"F10\"","Name=\"F8\""),LegacyText().Replace(IniHotkeys.BindingLine(IniHotkeys.Defaults[0])+"\r\n","")}){var p=Fixture("migration-blocked-"+Guid.NewGuid(),Encoding.UTF8.GetBytes(text));var bytes=File.ReadAllBytes(p.InputIni);Check(!new IniHotkeyService(new Probe(false)).MigrateLegacy(p.InputIni).Success);Check(File.ReadAllBytes(p.InputIni).SequenceEqual(bytes));}});
        test("migration works while running and failed replacement keeps old file",()=>{foreach(var running in new[]{true,false}){var p=Fixture("migration-failure-"+running,Encoding.UTF8.GetBytes(LegacyText()));var bytes=File.ReadAllBytes(p.InputIni);var result=new IniHotkeyService(new Probe(running),running?null:new FailingCommitter()).MigrateLegacy(p.InputIni);Check(running?result.Success:!result.Success&&File.ReadAllBytes(p.InputIni).SequenceEqual(bytes));}});
        test("missing or duplicate destination section refuses INI changes",()=>{foreach(var text in new[]{"[Other]\r\n",original+"[ColdGame.ColdPlayerInput]\r\n"}){var p=Fixture("missing-target-"+Guid.NewGuid(),Encoding.UTF8.GetBytes(text));Check(!new IniHotkeyService(new Probe(false)).Install(p.InputIni,IniHotkeys.Defaults).Success);Check(File.ReadAllText(p.InputIni)==text);}});
        const string cleanBase="[Engine.PlayerInput]\r\nBindings=(Name=\"W\",Command=\"GBA_MoveForward\")\r\nBindings=(Name=\"LeftMouseButton\",Command=\"GBA_Fire\")\r\n[ColdGame.ColdPlayerInput]\r\nbIsSprintToggle=TRUE\r\nbIsCrouchToggle=TRUE\r\nbIsAimDownSightsToggle=FALSE\r\n";
        test("clean installation uses inherited Engine bindings without shadowing flags",()=>{var doc=new InputIniDocument(Encoding.UTF8.GetBytes(cleanBase));Check(!doc.NeedsRepair);var installed=new InputIniDocument(doc.Install(IniHotkeys.Defaults));Check(!installed.NeedsRepair&&installed.HasCompleteLayout);Check(installed.Bindings.Where(b=>b.IsScs&&b.Section==InputIniDocument.ChildSection).All(b=>b.Operator=="."));Check(installed.RemoveScs().SequenceEqual(doc.OriginalBytes));});
        test("SCS-only plain child section migrates to pairs preserving foreign bytes and keys",()=>{foreach(var encoding in new Encoding[]{new UTF8Encoding(false),new UTF8Encoding(true),Encoding.Unicode,Encoding.BigEndianUnicode,Encoding.Latin1}){var block=InputIniDocument.Begin+"\r\n"+string.Join("\r\n",IniHotkeys.Defaults.Select(IniHotkeys.BindingLine))+"\r\n"+InputIniDocument.End+"\r\n";var bytes=encoding.GetPreamble().Concat(encoding.GetBytes(cleanBase+block)).ToArray();var p=Fixture("shadow-repair-"+encoding.WebName+encoding.GetPreamble().Length,bytes);Check(new InputIniDocument(bytes).NeedsRepair);var svc=new IniHotkeyService(new Probe(true));Check(svc.MigrateLegacy(p.InputIni).Success);var doc=new InputIniDocument(File.ReadAllBytes(p.InputIni));Check(!doc.NeedsRepair&&doc.Bindings.Count(b=>b.IsScs)==10&&doc.HasCompleteLayout);Check(doc.RemoveScs().SequenceEqual(encoding.GetPreamble().Concat(encoding.GetBytes(cleanBase))));Check(File.ReadAllBytes(Path.Combine(Path.GetDirectoryName(p.InputIni)!,"UDKInput.scs-backup.ini")).SequenceEqual(bytes));Check(!svc.MigrateLegacy(p.InputIni).Changed);}});
        test("normal child bindings remain unchanged alongside paired SCS bindings",()=>{var doc=new InputIniDocument(Encoding.UTF8.GetBytes(cleanBase+"Bindings=(Name=\"A\",Command=\"GBA_StrafeLeft\")\r\n"));Check(!doc.NeedsRepair);var result=new InputIniDocument(doc.Install(IniHotkeys.Defaults));Check(result.HasCompleteLayout);Check(result.RemoveScs().SequenceEqual(doc.OriginalBytes));});
        test("combined installation is available while game is running",()=>{var p=Fixture("combined-running",Encoding.UTF8.GetBytes(cleanBase));Check(new ManagedProfiles().Install(cat,Enum.GetValues<ProfileId>().Select(id=>ProfileRecord.CreateDefault(id,cat)),p.Binaries,IniHotkeys.Defaults,new Probe(true)).Success);Check(new InputIniDocument(File.ReadAllBytes(p.InputIni)).HasCompleteLayout);});
        var cleanFixture=Environment.GetEnvironmentVariable("SCS_CLEAN_INI_FIXTURE");
        if(cleanFixture is not null)test("supplied clean INI repairs SCS-only child without changing any original bytes",()=>{var bytes=File.ReadAllBytes(cleanFixture);var doc=new InputIniDocument(bytes);Check(!doc.Bindings.Any(b=>b.IsScs));var keys=Enum.GetValues<ProfileId>().Zip(IniHotkeys.AllowedKeys.Where(k=>doc.Conflicts(new(ProfileId.Profile1,k)).IsEmpty),(id,key)=>new HotkeyAssignment(id,key)).ToArray();Check(keys.Length==5);var block=InputIniDocument.Begin+doc.NewLine+string.Join(doc.NewLine,keys.Select(IniHotkeys.BindingLine))+doc.NewLine+InputIniDocument.End+doc.NewLine;var broken=doc.Encode(doc.Text.Replace("[ColdGame.ColdPlayerInput]"+doc.NewLine,"[ColdGame.ColdPlayerInput]"+doc.NewLine+block));var p=Fixture("actual-clean-repair",broken);Check(new IniHotkeyService(new Probe(true)).MigrateLegacy(p.InputIni).Success);var repaired=new InputIniDocument(File.ReadAllBytes(p.InputIni));Check(repaired.RemoveScs().SequenceEqual(bytes)&&!repaired.NeedsRepair);});
        test("local hotkey save acknowledges preferences without claiming installation",()=>{var session=new IniHotkeyEditSession();session.SetKey(ProfileId.Profile1,"Insert");Check(session.IsDirty);session.MarkPreferencesSaved();Check(!session.IsDirty&&session.GeneratedBinariesPath is null);Check(!session.Installed(new InputIniDocument(Encoding.UTF8.GetBytes(original))));});
        var fixture=Environment.GetEnvironmentVariable("SCS_INI_FIXTURE");
        if(fixture is not null)test("supplied UDKInput fixture preserves every unrelated byte and identifies F1-F9",()=>{var bytes=File.ReadAllBytes(fixture);var d=new InputIniDocument(bytes);foreach(var n in Enumerable.Range(1,9))Check(!d.Conflicts(new(ProfileId.Profile1,"F"+n)).IsEmpty,"F"+n);Check(IniHotkeys.Validate(IniHotkeys.Defaults,d).IsEmpty);Check(new InputIniDocument(d.Install(IniHotkeys.Defaults)).RemoveScs().SequenceEqual(bytes));var p=Fixture("user-ini",bytes);var svc=new IniHotkeyService(new Probe(false));Check(svc.Install(p.InputIni,IniHotkeys.Defaults).Success);Check(svc.Remove(p.InputIni).Success);Check(File.ReadAllBytes(p.InputIni).SequenceEqual(bytes));});
    }
    private sealed class Probe(bool running):IGameRunningProbe {public bool IsRunning()=>running;}
    private sealed class UnknownProbe:IGameRunningProbe {public bool IsRunning()=>throw new IOException("Unknown process state");}
    private sealed class ChangingProbe(Action action):IGameRunningProbe {private int count;public bool IsRunning(){if(++count==2)action();return false;}}
    private sealed class FailingCommitter:IAtomicCommitter {public void Commit(string t,string d,ExistingFileBehavior b)=>throw new IOException("Injected failure");}
}
